-- Ghiyarak Phase 6 Workshop & Automotive Service Operations
-- Services, workshop bookings, technicians, service orders, diagnostics, and vehicle maintenance history.

CREATE TABLE IF NOT EXISTS `workshop_services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `publicId` VARCHAR(191) NOT NULL,
  `organization_id` INT NOT NULL,
  `branch_id` INT NULL,
  `city_id` INT NULL,
  `created_by_user_id` INT NOT NULL,
  `name_ar` VARCHAR(180) NOT NULL,
  `name_en` VARCHAR(180) NULL,
  `category_code` VARCHAR(60) NOT NULL DEFAULT 'general',
  `description` TEXT NULL,
  `estimated_duration_minutes` INT NULL,
  `base_price` DECIMAL(12,2) NULL,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'YER',
  `requires_diagnosis` BOOLEAN NOT NULL DEFAULT false,
  `supports_mobile_service` BOOLEAN NOT NULL DEFAULT false,
  `status` ENUM('ACTIVE','PAUSED','ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `workshop_services_publicId_key` (`publicId`),
  KEY `workshop_services_organization_status_idx` (`organization_id`,`status`),
  KEY `workshop_services_branch_id_idx` (`branch_id`),
  KEY `workshop_services_city_status_idx` (`city_id`,`status`),
  CONSTRAINT `workshop_services_organization_id_fkey` FOREIGN KEY (`organization_id`) REFERENCES `org_organizations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `workshop_services_branch_id_fkey` FOREIGN KEY (`branch_id`) REFERENCES `org_organization_branches`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `workshop_services_city_id_fkey` FOREIGN KEY (`city_id`) REFERENCES `geo_cities`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `workshop_services_created_by_user_id_fkey` FOREIGN KEY (`created_by_user_id`) REFERENCES `iam_users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `workshop_technicians` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `publicId` VARCHAR(191) NOT NULL,
  `organization_id` INT NOT NULL,
  `branch_id` INT NULL,
  `user_id` INT NULL,
  `full_name` VARCHAR(140) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `specializations` JSON NULL,
  `status` ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  `max_jobs_per_day` INT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `workshop_technicians_publicId_key` (`publicId`),
  KEY `workshop_technicians_organization_status_idx` (`organization_id`,`status`),
  KEY `workshop_technicians_branch_id_idx` (`branch_id`),
  CONSTRAINT `workshop_technicians_organization_id_fkey` FOREIGN KEY (`organization_id`) REFERENCES `org_organizations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `workshop_technicians_branch_id_fkey` FOREIGN KEY (`branch_id`) REFERENCES `org_organization_branches`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `workshop_technicians_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `iam_users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `workshop_bookings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `publicId` VARCHAR(191) NOT NULL,
  `user_id` INT NOT NULL,
  `customer_vehicle_id` INT NULL,
  `organization_id` INT NOT NULL,
  `branch_id` INT NULL,
  `workshop_service_id` INT NOT NULL,
  `city_id` INT NULL,
  `technician_id` INT NULL,
  `status` ENUM('REQUESTED','CONFIRMED','IN_PROGRESS','COMPLETED','CANCELLED','REJECTED') NOT NULL DEFAULT 'REQUESTED',
  `preferred_date` DATETIME(3) NOT NULL,
  `preferred_time_window` VARCHAR(60) NULL,
  `customer_problem_description` TEXT NULL,
  `customer_note` VARCHAR(500) NULL,
  `workshop_note` VARCHAR(500) NULL,
  `estimated_amount` DECIMAL(12,2) NULL,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'YER',
  `cancellation_reason` VARCHAR(500) NULL,
  `cancelled_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `workshop_bookings_publicId_key` (`publicId`),
  KEY `workshop_bookings_user_status_idx` (`user_id`,`status`),
  KEY `workshop_bookings_organization_status_idx` (`organization_id`,`status`),
  KEY `workshop_bookings_preferred_date_idx` (`preferred_date`),
  CONSTRAINT `workshop_bookings_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `iam_users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `workshop_bookings_customer_vehicle_id_fkey` FOREIGN KEY (`customer_vehicle_id`) REFERENCES `vehicle_customer_vehicles`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `workshop_bookings_organization_id_fkey` FOREIGN KEY (`organization_id`) REFERENCES `org_organizations`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `workshop_bookings_branch_id_fkey` FOREIGN KEY (`branch_id`) REFERENCES `org_organization_branches`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `workshop_bookings_workshop_service_id_fkey` FOREIGN KEY (`workshop_service_id`) REFERENCES `workshop_services`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `workshop_bookings_city_id_fkey` FOREIGN KEY (`city_id`) REFERENCES `geo_cities`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `workshop_bookings_technician_id_fkey` FOREIGN KEY (`technician_id`) REFERENCES `workshop_technicians`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `workshop_booking_status_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `booking_id` INT NOT NULL,
  `status` ENUM('REQUESTED','CONFIRMED','IN_PROGRESS','COMPLETED','CANCELLED','REJECTED') NOT NULL,
  `changed_by_user_id` INT NULL,
  `note` VARCHAR(500) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `workshop_booking_status_history_booking_id_idx` (`booking_id`),
  CONSTRAINT `workshop_booking_status_history_booking_id_fkey` FOREIGN KEY (`booking_id`) REFERENCES `workshop_bookings`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `workshop_booking_status_history_changed_by_user_id_fkey` FOREIGN KEY (`changed_by_user_id`) REFERENCES `iam_users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `workshop_service_orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `publicId` VARCHAR(191) NOT NULL,
  `service_order_number` VARCHAR(40) NOT NULL,
  `user_id` INT NOT NULL,
  `customer_vehicle_id` INT NULL,
  `organization_id` INT NOT NULL,
  `branch_id` INT NULL,
  `booking_id` INT NULL,
  `workshop_service_id` INT NULL,
  `technician_id` INT NULL,
  `status` ENUM('OPEN','DIAGNOSIS_IN_PROGRESS','WAITING_CUSTOMER_APPROVAL','WAITING_PARTS','IN_REPAIR','READY_FOR_DELIVERY','COMPLETED','CANCELLED') NOT NULL DEFAULT 'OPEN',
  `priority` ENUM('LOW','NORMAL','HIGH','URGENT') NOT NULL DEFAULT 'NORMAL',
  `problem_description` TEXT NULL,
  `diagnosis_summary` TEXT NULL,
  `work_summary` TEXT NULL,
  `estimated_amount` DECIMAL(12,2) NULL,
  `approved_amount` DECIMAL(12,2) NULL,
  `final_amount` DECIMAL(12,2) NULL,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'YER',
  `customer_approval_required` BOOLEAN NOT NULL DEFAULT false,
  `customer_approved_at` DATETIME(3) NULL,
  `started_at` DATETIME(3) NULL,
  `completed_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `workshop_service_orders_publicId_key` (`publicId`),
  UNIQUE KEY `workshop_service_orders_number_key` (`service_order_number`),
  UNIQUE KEY `workshop_service_orders_booking_id_key` (`booking_id`),
  KEY `workshop_service_orders_user_status_idx` (`user_id`,`status`),
  KEY `workshop_service_orders_organization_status_idx` (`organization_id`,`status`),
  KEY `workshop_service_orders_number_idx` (`service_order_number`),
  CONSTRAINT `workshop_service_orders_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `iam_users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `workshop_service_orders_customer_vehicle_id_fkey` FOREIGN KEY (`customer_vehicle_id`) REFERENCES `vehicle_customer_vehicles`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `workshop_service_orders_organization_id_fkey` FOREIGN KEY (`organization_id`) REFERENCES `org_organizations`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `workshop_service_orders_branch_id_fkey` FOREIGN KEY (`branch_id`) REFERENCES `org_organization_branches`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `workshop_service_orders_booking_id_fkey` FOREIGN KEY (`booking_id`) REFERENCES `workshop_bookings`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `workshop_service_orders_workshop_service_id_fkey` FOREIGN KEY (`workshop_service_id`) REFERENCES `workshop_services`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `workshop_service_orders_technician_id_fkey` FOREIGN KEY (`technician_id`) REFERENCES `workshop_technicians`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `workshop_service_order_status_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `service_order_id` INT NOT NULL,
  `status` ENUM('OPEN','DIAGNOSIS_IN_PROGRESS','WAITING_CUSTOMER_APPROVAL','WAITING_PARTS','IN_REPAIR','READY_FOR_DELIVERY','COMPLETED','CANCELLED') NOT NULL,
  `changed_by_user_id` INT NULL,
  `note` VARCHAR(500) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `workshop_service_order_status_history_service_order_id_idx` (`service_order_id`),
  CONSTRAINT `workshop_service_order_status_history_service_order_id_fkey` FOREIGN KEY (`service_order_id`) REFERENCES `workshop_service_orders`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `workshop_service_order_status_history_changed_by_user_id_fkey` FOREIGN KEY (`changed_by_user_id`) REFERENCES `iam_users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `workshop_diagnostic_reports` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `publicId` VARCHAR(191) NOT NULL,
  `service_order_id` INT NOT NULL,
  `technician_id` INT NULL,
  `symptoms` TEXT NULL,
  `findings` TEXT NOT NULL,
  `recommended_actions` TEXT NULL,
  `estimated_repair_cost` DECIMAL(12,2) NULL,
  `requires_parts` BOOLEAN NOT NULL DEFAULT false,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `workshop_diagnostic_reports_publicId_key` (`publicId`),
  KEY `workshop_diagnostic_reports_service_order_id_idx` (`service_order_id`),
  CONSTRAINT `workshop_diagnostic_reports_service_order_id_fkey` FOREIGN KEY (`service_order_id`) REFERENCES `workshop_service_orders`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `workshop_diagnostic_reports_technician_id_fkey` FOREIGN KEY (`technician_id`) REFERENCES `workshop_technicians`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `vehicle_maintenance_records` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `publicId` VARCHAR(191) NOT NULL,
  `user_id` INT NOT NULL,
  `customer_vehicle_id` INT NOT NULL,
  `organization_id` INT NULL,
  `service_order_id` INT NULL,
  `title` VARCHAR(180) NOT NULL,
  `description` TEXT NULL,
  `mileage` INT NULL,
  `service_date` DATETIME(3) NOT NULL,
  `next_service_date` DATETIME(3) NULL,
  `cost_amount` DECIMAL(12,2) NULL,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'YER',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `vehicle_maintenance_records_publicId_key` (`publicId`),
  KEY `vehicle_maintenance_records_user_service_date_idx` (`user_id`,`service_date`),
  KEY `vehicle_maintenance_records_vehicle_service_date_idx` (`customer_vehicle_id`,`service_date`),
  CONSTRAINT `vehicle_maintenance_records_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `iam_users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `vehicle_maintenance_records_customer_vehicle_id_fkey` FOREIGN KEY (`customer_vehicle_id`) REFERENCES `vehicle_customer_vehicles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `vehicle_maintenance_records_organization_id_fkey` FOREIGN KEY (`organization_id`) REFERENCES `org_organizations`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `vehicle_maintenance_records_service_order_id_fkey` FOREIGN KEY (`service_order_id`) REFERENCES `workshop_service_orders`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
