-- Ghiyarak Phase 7 Payments, Delivery & FCM Notification Foundation
-- Manual payment transactions, shipment lifecycle, tracking events, device tokens, and in-app notification outbox.

CREATE TABLE IF NOT EXISTS `payment_transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `publicId` VARCHAR(191) NOT NULL,
  `order_id` INT NULL,
  `service_order_id` INT NULL,
  `payer_user_id` INT NULL,
  `organization_id` INT NULL,
  `type` ENUM('ORDER_PAYMENT','SERVICE_ORDER_PAYMENT','REFUND','ADJUSTMENT') NOT NULL DEFAULT 'ORDER_PAYMENT',
  `provider` ENUM('MANUAL','CASH','BANK_TRANSFER','WALLET','EXTERNAL') NOT NULL DEFAULT 'MANUAL',
  `payment_method` ENUM('CASH_ON_DELIVERY','CASH_ON_PICKUP','BANK_TRANSFER','WALLET') NULL,
  `status` ENUM('INITIATED','PENDING_REVIEW','AUTHORIZED','PAID','FAILED','CANCELLED','REFUNDED') NOT NULL DEFAULT 'INITIATED',
  `amount` DECIMAL(12,2) NOT NULL,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'YER',
  `internal_reference` VARCHAR(80) NOT NULL,
  `external_reference` VARCHAR(120) NULL,
  `receipt_url` VARCHAR(500) NULL,
  `review_note` VARCHAR(500) NULL,
  `metadata_json` JSON NULL,
  `paid_at` DATETIME(3) NULL,
  `failed_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `payment_transactions_publicId_key` (`publicId`),
  UNIQUE KEY `payment_transactions_internal_reference_key` (`internal_reference`),
  KEY `payment_transactions_order_status_idx` (`order_id`,`status`),
  KEY `payment_transactions_service_order_status_idx` (`service_order_id`,`status`),
  KEY `payment_transactions_payer_status_idx` (`payer_user_id`,`status`),
  KEY `payment_transactions_org_status_idx` (`organization_id`,`status`),
  CONSTRAINT `payment_transactions_order_id_fkey` FOREIGN KEY (`order_id`) REFERENCES `commerce_orders`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `payment_transactions_service_order_id_fkey` FOREIGN KEY (`service_order_id`) REFERENCES `workshop_service_orders`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `payment_transactions_payer_user_id_fkey` FOREIGN KEY (`payer_user_id`) REFERENCES `iam_users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `payment_transactions_organization_id_fkey` FOREIGN KEY (`organization_id`) REFERENCES `org_organizations`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `delivery_methods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(50) NOT NULL,
  `name_ar` VARCHAR(120) NOT NULL,
  `name_en` VARCHAR(120) NULL,
  `description` VARCHAR(500) NULL,
  `base_fee` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'YER',
  `estimated_duration_text` VARCHAR(120) NULL,
  `supports_cash_on_delivery` BOOLEAN NOT NULL DEFAULT true,
  `status` ENUM('ACTIVE','PAUSED') NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `delivery_methods_code_key` (`code`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `delivery_shipments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `publicId` VARCHAR(191) NOT NULL,
  `shipment_number` VARCHAR(40) NOT NULL,
  `order_id` INT NOT NULL,
  `organization_id` INT NOT NULL,
  `branch_id` INT NULL,
  `city_id` INT NULL,
  `delivery_method_id` INT NULL,
  `created_by_user_id` INT NOT NULL,
  `status` ENUM('PENDING','READY_FOR_PICKUP','PICKED_UP','IN_TRANSIT','OUT_FOR_DELIVERY','DELIVERED','FAILED','CANCELLED','RETURNED') NOT NULL DEFAULT 'PENDING',
  `tracking_number` VARCHAR(80) NULL,
  `courier_name` VARCHAR(120) NULL,
  `recipient_name` VARCHAR(120) NULL,
  `recipient_phone` VARCHAR(20) NULL,
  `delivery_address` VARCHAR(500) NULL,
  `delivery_fee` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'YER',
  `notes` VARCHAR(500) NULL,
  `estimated_pickup_at` DATETIME(3) NULL,
  `estimated_delivery_at` DATETIME(3) NULL,
  `picked_up_at` DATETIME(3) NULL,
  `delivered_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `delivery_shipments_publicId_key` (`publicId`),
  UNIQUE KEY `delivery_shipments_number_key` (`shipment_number`),
  UNIQUE KEY `delivery_shipments_order_id_key` (`order_id`),
  UNIQUE KEY `delivery_shipments_tracking_number_key` (`tracking_number`),
  KEY `delivery_shipments_org_status_idx` (`organization_id`,`status`),
  KEY `delivery_shipments_city_status_idx` (`city_id`,`status`),
  KEY `delivery_shipments_status_idx` (`status`),
  CONSTRAINT `delivery_shipments_order_id_fkey` FOREIGN KEY (`order_id`) REFERENCES `commerce_orders`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `delivery_shipments_organization_id_fkey` FOREIGN KEY (`organization_id`) REFERENCES `org_organizations`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `delivery_shipments_branch_id_fkey` FOREIGN KEY (`branch_id`) REFERENCES `org_organization_branches`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `delivery_shipments_city_id_fkey` FOREIGN KEY (`city_id`) REFERENCES `geo_cities`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `delivery_shipments_delivery_method_id_fkey` FOREIGN KEY (`delivery_method_id`) REFERENCES `delivery_methods`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `delivery_shipments_created_by_user_id_fkey` FOREIGN KEY (`created_by_user_id`) REFERENCES `iam_users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `delivery_shipment_tracking_events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `shipment_id` INT NOT NULL,
  `status` ENUM('PENDING','READY_FOR_PICKUP','PICKED_UP','IN_TRANSIT','OUT_FOR_DELIVERY','DELIVERED','FAILED','CANCELLED','RETURNED') NOT NULL,
  `note` VARCHAR(500) NULL,
  `location_text` VARCHAR(180) NULL,
  `changed_by_user_id` INT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `delivery_events_shipment_id_idx` (`shipment_id`),
  CONSTRAINT `delivery_events_shipment_id_fkey` FOREIGN KEY (`shipment_id`) REFERENCES `delivery_shipments`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `delivery_events_changed_by_user_id_fkey` FOREIGN KEY (`changed_by_user_id`) REFERENCES `iam_users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `notification_user_devices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `publicId` VARCHAR(191) NOT NULL,
  `user_id` INT NOT NULL,
  `platform` ENUM('ANDROID','IOS','WEB','WINDOWS','MACOS','LINUX','UNKNOWN') NOT NULL DEFAULT 'UNKNOWN',
  `fcm_token` VARCHAR(512) NOT NULL,
  `device_name` VARCHAR(120) NULL,
  `app_version` VARCHAR(40) NULL,
  `is_active` BOOLEAN NOT NULL DEFAULT true,
  `last_seen_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `notification_user_devices_publicId_key` (`publicId`),
  UNIQUE KEY `notification_user_devices_fcm_token_key` (`fcm_token`),
  KEY `notification_user_devices_user_active_idx` (`user_id`,`is_active`),
  CONSTRAINT `notification_user_devices_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `iam_users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `publicId` VARCHAR(191) NOT NULL,
  `user_id` INT NOT NULL,
  `channel` ENUM('IN_APP','FCM') NOT NULL DEFAULT 'IN_APP',
  `title` VARCHAR(160) NOT NULL,
  `body` VARCHAR(500) NOT NULL,
  `data` JSON NULL,
  `status` ENUM('UNREAD','READ','ARCHIVED') NOT NULL DEFAULT 'UNREAD',
  `read_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `notifications_publicId_key` (`publicId`),
  KEY `notifications_user_status_idx` (`user_id`,`status`),
  KEY `notifications_created_at_idx` (`created_at`),
  CONSTRAINT `notifications_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `iam_users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
