CREATE TABLE IF NOT EXISTS `product_import_templates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `public_id` VARCHAR(191) NOT NULL,
  `name` VARCHAR(140) NOT NULL,
  `organization_type` VARCHAR(30) NULL,
  `required_columns` JSON NOT NULL,
  `optional_columns` JSON NULL,
  `sample_rows` JSON NULL,
  `is_default` BOOLEAN NOT NULL DEFAULT false,
  `is_active` BOOLEAN NOT NULL DEFAULT true,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `product_import_templates_public_id_key` (`public_id`),
  INDEX `product_import_templates_org_type_active_idx` (`organization_type`, `is_active`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `product_import_mappings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `organization_id` INT NULL,
  `template_id` INT NULL,
  `source_column` VARCHAR(120) NOT NULL,
  `target_field` VARCHAR(120) NOT NULL,
  `is_required` BOOLEAN NOT NULL DEFAULT false,
  `default_value` VARCHAR(255) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_import_mappings_organization_id_idx` (`organization_id`),
  INDEX `product_import_mappings_template_id_idx` (`template_id`),
  CONSTRAINT `product_import_mappings_organization_id_fkey` FOREIGN KEY (`organization_id`) REFERENCES `org_organizations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `product_import_mappings_template_id_fkey` FOREIGN KEY (`template_id`) REFERENCES `product_import_templates`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `product_import_jobs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `public_id` VARCHAR(191) NOT NULL,
  `organization_id` INT NOT NULL,
  `branch_id` INT NOT NULL,
  `uploaded_by_user_id` INT NOT NULL,
  `file_name` VARCHAR(255) NOT NULL,
  `original_file_name` VARCHAR(255) NOT NULL,
  `file_mime_type` VARCHAR(120) NULL,
  `file_size_bytes` INT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'UPLOADED',
  `total_rows` INT NOT NULL DEFAULT 0,
  `valid_rows` INT NOT NULL DEFAULT 0,
  `invalid_rows` INT NOT NULL DEFAULT 0,
  `imported_rows` INT NOT NULL DEFAULT 0,
  `skipped_rows` INT NOT NULL DEFAULT 0,
  `currency` VARCHAR(3) NOT NULL DEFAULT 'YER',
  `parsed_at` DATETIME(3) NULL,
  `confirmed_at` DATETIME(3) NULL,
  `completed_at` DATETIME(3) NULL,
  `failed_reason` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `product_import_jobs_public_id_key` (`public_id`),
  INDEX `product_import_jobs_organization_created_idx` (`organization_id`, `created_at`),
  INDEX `product_import_jobs_branch_id_idx` (`branch_id`),
  INDEX `product_import_jobs_uploaded_by_user_id_idx` (`uploaded_by_user_id`),
  INDEX `product_import_jobs_status_idx` (`status`),
  CONSTRAINT `product_import_jobs_organization_id_fkey` FOREIGN KEY (`organization_id`) REFERENCES `org_organizations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `product_import_jobs_branch_id_fkey` FOREIGN KEY (`branch_id`) REFERENCES `org_organization_branches`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `product_import_jobs_uploaded_by_user_id_fkey` FOREIGN KEY (`uploaded_by_user_id`) REFERENCES `iam_users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `product_import_rows` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `job_id` INT NOT NULL,
  `row_number` INT NOT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'PENDING',
  `raw_data` JSON NOT NULL,
  `normalized_data` JSON NULL,
  `error_summary` TEXT NULL,
  `product_id` INT NULL,
  `listing_id` INT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `product_import_rows_job_row_uq` (`job_id`, `row_number`),
  INDEX `product_import_rows_job_status_idx` (`job_id`, `status`),
  INDEX `product_import_rows_product_id_idx` (`product_id`),
  INDEX `product_import_rows_listing_id_idx` (`listing_id`),
  CONSTRAINT `product_import_rows_job_id_fkey` FOREIGN KEY (`job_id`) REFERENCES `product_import_jobs`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `product_import_rows_product_id_fkey` FOREIGN KEY (`product_id`) REFERENCES `catalog_products`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `product_import_rows_listing_id_fkey` FOREIGN KEY (`listing_id`) REFERENCES `market_listings`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `product_import_errors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `job_id` INT NOT NULL,
  `row_id` INT NULL,
  `field_name` VARCHAR(120) NULL,
  `error_code` VARCHAR(80) NOT NULL,
  `message` VARCHAR(500) NOT NULL,
  `value` VARCHAR(500) NULL,
  `severity` VARCHAR(30) NOT NULL DEFAULT 'ERROR',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `product_import_errors_job_id_idx` (`job_id`),
  INDEX `product_import_errors_row_id_idx` (`row_id`),
  INDEX `product_import_errors_error_code_idx` (`error_code`),
  CONSTRAINT `product_import_errors_job_id_fkey` FOREIGN KEY (`job_id`) REFERENCES `product_import_jobs`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `product_import_errors_row_id_fkey` FOREIGN KEY (`row_id`) REFERENCES `product_import_rows`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
